### PR TITLE
Style CIF Core Components

### PR DESCRIPTION
**Pull request by godanny86**
- introduction tutorial for styling CIF Core Components

### CODE REVIEW

**Comment by godanny86** [comment]
can preview the tutorial here: https://github.com/godanny86/commerce-cif-documentation/blob/doc/cif-style-component/tutorials/04-style-cif-component.md

**Review by mhaack — APPROVED** [review]
Very detailed. 👍

**Comment by mhaack** [comment]
The first steps of "Generate a project" might change very soon, once we merged the CIF archetype with AEM project archetype. @aditidc should we wait with this tutorial? (I don't know when the merge will be done, but will be after AEM archetype release 23.

**Comment by godanny86** [comment]
i'd say lets merge it as is and then can revisit once CIF archetype has been moved...

**Pull request merged**
